output: ${environment.remote_str}/result/
ddp: False

cmd: ". /ws-judyye/dex_afford/src/docs/jit_pip.sh"
local_str: /tmp/ws/
remote_str: /ws-judyye/

local_dir: ${environment.local_str}/result/
remote_dir: ${environment.remote_str}/result/

org: nvidian
team: lpr
ace: nv-us-west-2
preempt: RUNONCE
image: nvcr.io/nvidian/lpr/pt19_cuda113:afford
ngpu: 1
result: /result  # mount location

workspace: 'ws-judyye'
time: 72
data: 102373:ho3d+109663:obman
instance: dgx1v.${environment.mem}g.${environment.ngpu}.norm
mem: 16

slurm: True
overwrite: False